config/routes.rb
Moshemishali::Application.routes.draw do
  resources :videos
  resources :home









  root :to => "pages#home"
  get "/Index.aspx" => "pages#redirect_to_home"

end

app/models/video.rb
class Video < ActiveRecord::Base
	attr_accessible :description, :title, :url, :typename, :image_url, :synopsis

	def is_valid
		(nil != (self.typename =~ /filmography/)) or 
		(nil != (self.typename =~ /music_video|film|commercial/) and nil != (self.image_url =~ /jpg|png|gif/))
	end

	def self.invalids
		Video.all.select{|v| !v.is_valid}
	end

	def self.by_type(typename)
		Video.find_all_by_typename(typename).sort_by{|v| v.created_at}
	end

	def self.create_all
		Video.delete_all
		Video.create_commercials
		Video.create_musicvideos
		Video.create_films
		Video.create_filmography
	end

	private

	@@ytb = "http://www.youtube-nocookie.com/embed/"
	
	def self.create_commercials
		Video.create({
			:title =>  "Maccabi Beer - Sound Check",
			:image_url =>  "Posters/commercial/maccabi_soundcheck.jpg",
			:url =>  @@ytb + "MXsNeMFwrA4",
			:description =>  "with Asaf Avidan;Director - Adam bizanski;2nd Unit cinematography - Eli Aharonson",
			:typename =>  "commercial"	
			})	

		Video.create({
			:title => "Maccabi Home Tour - The SMS",
			:image_url => "Posters/commercial/maccabi_sms.jpg",
			:url => @@ytb + "vAzjqpfmpBc",
			:description => "with Shlomi Shaban;Director - Adam bizanski",
			:typename => "commercial"
			})		

		Video.create({
			:title => "Maccabi Home Tour - Big Time",
			:image_url => "Posters/commercial/maccabi_bigtime.jpg",
			:url => @@ytb + "i_s6ErUTvCg",
			:description => "with Shlomi Shaban;Director - Adam bizanski",
			:typename => "commercial"
			})
		
		Video.create({
			:title => "Maccabi Home Tour - The Monolog",
			:image_url => "Posters/commercial/maccabi_monolog.jpg",
			:url => @@ytb + "CiFbEHC0TVc",
			:description => "with Shlomi Shaban;Director - Adam bizanski",
			:typename => "commercial"
			})
		

		Video.create({
			:title => "El Namrod",
			:image_url => "Posters/commercial/elnamroud.jpg",
			:url => @@ytb + "DGN_XvqvlTs",
			:description => "Directors - Tal Greenberg &amp; Yasmin Shryer;Additional Cinematography - Roee Mandelevitch",
			:typename => "commercial"
			})
		

		Video.create({
			:title => "MyCheck",
			:image_url => "Posters/commercial/mycheck.jpg",
			:url => @@ytb + "hcgOdQQonN4",
			:description => "Director - Vania Heymann",
			:typename => "commercial"
			})
		

		Video.create({
			:title => "American Express - The Young Professionals Project",
			:image_url => "Posters/commercial/typ.jpg",
			:url => @@ytb + "uHZo6c0Fvgg",
			:description => "Director - Vania Heymann",
			:typename => "commercial"
			})
		

		Video.create({
			:title => "Pepsi Max",
			:image_url => "Posters/commercial/pepsimax.jpg",
			:url => @@ytb + "gfpW-hKx2Yg",
			:description => "Director - Vania Heymann",
			:typename => "commercial"
			})
		

		Video.create({
			:title => "Soundcheck - Aviv Geffen",
			:image_url => "Posters/commercial/maccabi_avivgeffen.jpg",
			:url => @@ytb + "djr3cIVRGgw",
			:description => "Director - Adam Bizanski",
			:typename => "commercial"
			})
		

		logger.info("Created " + i.to_s + " commercials")
	end


	def self.create_musicvideos
		
		Video.create({
			:title => "Amsterdam",
			:image_url => "Posters/musicvideos/amsterdam.jpg",
			:url => @@ytb + "URQDqaOIq6s",
			:description => "Hageveret Harishona;Director - Adi Yager",
			:typename => "music_video"
			})
		

		Video.create({
			:title => "Too Afraid to Love You",
			:image_url => "Posters/musicvideos/tooafraid.jpg",
			:description => "Black Keys;Director - Adam bizanski",
			:url => @@ytb + "Ft_-5kuYY-E",
			:typename => "music_video"
			})
		

		Video.create({
			:title => "A Secret Day",
			:image_url => "Posters/musicvideos/secretday.jpg",
			:description => "Omer Leshem;Director - Asaph Polonsky",
			:url => @@ytb + "eGbItkCl1g4",
			:typename => "music_video"
			})
		

		Video.create({
			:title => "Halomot Ra&quot;im (Bad Dreams)",
			:image_url => "Posters/musicvideos/baddreams.jpg",
			:description => "Cohen @ Mushon;Director - Gal Muggia",
			:url => @@ytb + "qqZ1HwLMoro",
			:typename => "music_video"
			})
		

		logger.info("Created " + i.to_s + " music videos")
	end

	def self.create_films
		
		v = Video.new()
		v[:title] = "Paul" 
		v[:image_url] = "Posters/films/paul.jpg"
		v[:description] = "Israel 2011, 26min;Director : Adam Bizanski"
		v[:url] = @@ytb + "1xEReh8ygnU"
		v[:synopsis] = "Still in the aftermath of a tough break up, Paul&quot;s life is slowly deteriorating."
		v[:synopsis] += " A mindless burglary of his rented apartment forces him to to push through the underworld"
		v[:synopsis] += " of Tel Avivto investigate.;;"
		v[:synopsis] += "<b>Haifa International Film Festival</b> - 2011" 
		v[:typename] = "film"
		v.save
		

		v = Video.new()
		v[:title] = "Martha Must Fly" 
		v[:image_url] = "Posters/films/martha.jpg" 
		v[:description] = "Israel 2011, 26min;Director : Ma&quot;ayan Rypp;"
		v[:url] = @@ytb + "Kjc4ooThuO8"
		v[:synopsis] = "Martha is a foreign worker employed as a caretaker of sick old woman who refuses to die."
		v[:synopsis] += " Martha&quot;s only moments of freedom come when she delves into her imaginary world."
		v[:synopsis] += " Feeling trapped and lonely, Martha tries to free herself but the authorities make it"
		v[:synopsis] += " clear to her that until the old woman dies she must stay. She decides to fight for her"
		v[:synopsis] += " freedom but reality pushes her into her fantasy world, one last time.;;<b>"
		v[:synopsis] += "Cannes - Cinefoundation</b> - official selection 2011;<b>Jerusalem International Film"
		v[:synopsis] += " Festival</b> - Israeli Short Film Competition 2011;"
		v[:synopsis] += "<b>Cyprus International Short Film Festival</b> - 2011 - Received Special Mention for"
		v[:synopsis] += " Best Actress and Official Students Choice.;"
		v[:synopsis] += "<b>Rehovot Women&quot;s Film Festival</b> - nominated for Best Drama and winner of"
		v[:synopsis] += " most Promising Director;<b>Lodz 18th International Film and TV Schools"
		v[:synopsis] += " Festival &quot;MEDIASCHOOL 2011&quot;</b>;<b>International Student and Video Festival"
		v[:synopsis] += " of Beijing Film Academy</b> - 2011;"
		v[:synopsis] += "<b>New Taipei City Film Festival</b> - Panorama Program, 2011"
		v[:typename] = "film"
		v.save
		

		v = Video.new()
		v[:title] = "In Bed at 10pm" 
		v[:image_url] = "Posters/films/bed.jpg" 
		v[:description] = "Israel 2010, 15min;Director : Asaph Polonsky"
		v[:url] = @@ytb + "AwgqgWsyax8"
		v[:synopsis] = "Rachel is a librarian; she knows all about how language works."
		v[:synopsis] += " When her lover&quot;s mobile phone rings twice during a sleep over in her flat,"
		v[:synopsis] += " he informs her of its meaning."
		v[:synopsis] += " His wife needs him, it is urgent and overrides their arrangement that he keep a mistress."
		v[:synopsis] += " At 70, how will Rachel find a love deeper than Motti&quot;s and move from mistress to top"
		v[:synopsis] += " billing? She must act."
		v[:synopsis] += " With the help of a younger colleague, she \"tweaks\" her internet profile and begins"
		v[:synopsis] += " the dispiriting process of dating. Disappointment is everywhere, just as it is for"
		v[:synopsis] += " younger wannabe lovers."
		v[:synopsis] += " It&quot;s not so much a moral dilemma as a literary one.;;<b>CFC - Toronto International"
		v[:synopsis] += " Film Festival</b> - 2011;<b>MIFF - Milano International Film Festival</b> - 2011;"
		v[:synopsis] += "<b>L.A. Shorts Fest</b> - 2011;<b>Jerusalm International Film Festival</b> - 2010"
		v[:typename] = "film"
		v.save
		

		Video.create({
			:title => "Private Rooms",
			:image_url => "Posters/films/privaterooms.jpg",
			:typename => "film"
			})
		

		v = Video.new()
		v[:title] = "Zipper"
		v[:image_url] = "Posters/films/zipper.jpg"
		v[:description] = "Israel 2008, 34min;Director : Asaph Polonsky"
		v[:url] = @@ytb + "g84VOBqisaQ"
		v[:synopsis] = "Surrounded by fake landscapes formed by jigsaw puzzles and being dependent upon"
		v[:synopsis] += " high dosage of tranquilizers, the fragile reality that Yaki has built for himself"
		v[:synopsis] += " during his compulsory solitude will shatter in face of the complex relationship"
		v[:synopsis] += " that would ensue with the stranger invading his house - and life.;;"
		v[:synopsis] += "<b>Mexico Film Festival 2010</b> - Silver Palm Award Winner;<b>Jerusalem International "
		v[:synopsis] += " Film Festival</b> - 2009;<b>Akbank Short Film Festival</b> - 2008;<b>Miami Short Film "
		v[:synopsis] += " Festival</b> - 2008;<b>Boston Jewish Film Festival</b> - 2009;<b>Real to Reel Film Festival</b>"
		v[:synopsis] += " - 2009;<b>Glimmer: the 7th Hull International Film Festival</b> - 2009"
		v[:typename] = "film"
		v.save
		

		Video.create({
			:title => "The Thirsty Man",
			:image_url => "Posters/films/thirsty.jpg",
			:description => "Israel 2012, 6min;Director: Eitan Aner",
			:url => @@ytb + "FIBSTK4ndHM",
			:typename => "film"
			})
		

		# v = Video.new()
		# v[:title] = "Batman at the Checkpoint"
		# v[:image_url] = "Posters/films/batman.jpg"
		# v[:description] = "Israel 2011, 9min;Director: Rafael Balulu"
		# v[:url] = ""
		# v[:synopsis] = "An Israeli car and a Palestinian car are stuck in traffic in front of a barricade at the entrance of Jerusalem,"
		# v[:synopsis] += " coming from the Dead Sea. Yuval and Mahmoud, both two six-year-old boys, find that it&quot;s much more fun to"
		# v[:synopsis] += " pass the time playing with one another. But when Mahmoud&quot;s father tries to cut into the other&quot;s lane,"
		# v[:synopsis] += " Yuval&quot;s father bumps into his car in an attempt to prevent him, and things start to get complicated."

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :verify_admin, :only => [:index]

  @@ADMIN_PASS = "44353261"

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.select{|v| v.is_visible and v.is_valid}.sort_by{|v| v[:created_at]}.reverse

    respond_to do |format|
      format.html { render :layout => false } #index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id]) 

    respond_to do |format|
      format.html { render :layout => false } #show.html.erb
      format.json { render json: @video } 
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    if !@video.image_url and @video.url =~ /youtube/
      @video.image_url = "http://img.youtube.com/vi/" + @video.url.split("/embed/").last + "/default.jpg"
    end

    respond_to do |format|
      if @video.save
        format.html { redirect_to "/videos?p=" + @@ADMIN_PASS }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new", :layout => false }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to "/videos?p=" + @@ADMIN_PASS }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    # @video.destroy

    @video.is_visible = false

    respond_to do |format|
      if @video.save
        format.html { redirect_to "/videos?p=" + @@ADMIN_PASS }
        format.json { render json: {:video => @video.to_json}  }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def verify_admin
    if params[:p] != @@ADMIN_PASS
      redirect_to :root
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_filmography_section.html.erb
<div class="sectionheader"><%= title %></div>
<ul>
	<% Video.by_type(type).each do |f| %>
	<li>
		<span><%= f.title.gsub("&#150;", "-") %></span> 
		<%= f.description.gsub("&#150;", "-") %>
	</li>
	<% end %>
</ul>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
<% if @video.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

  <ul>
    <% @video.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :typename %>
  <%= f.select(:typename, [["Music Video", "music_video"], ["Commercial", "commercial"],["Film", "film"]]) %>
</div>
<div class="field">
  <%= f.label :url %>
  <%= f.text_field :url, :placeholder => "Video embed URL: http://www.youtube-nocookie.com/embed/<Video ID>" %>
</div>
<div class="field">
  <%= f.label :image_url %>
  <%= f.text_field :image_url, :placeholder => "Link to an image (i.e. http://www.moshemishali.com/logo.jpg)" %>
</div>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => "Name of the video" %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, :rows => "5", :placeholder => "The line below the video (i.e. 'Directed by...')" %>
</div>
<div class="actions">
  <%= f.submit "Create", :id => "save" %>
</div>
<% end %>

app/views/videos/_gallery.html.erb
<div class="pageheader"><%= title %></div>
<div class="gallery <%= css_class %>">
	<% Video.by_type(typename).reverse.each do |v| %>
	<div class="video <%= typename %>" data-title="<%= v.title.to_s %>">
		<a class="watch<%= " soon" if !v.url %>" data_url="<%= v.url %>" href="javascript:void(0);">
			<img src="<%= asset_path v.image_url %>" />
		</a>
		<span class="text">
			<span class="title"><%= raw v.title.to_s.gsub("&quot;","'").gsub(";","<br>") %></span>
			<span class="desc"><%= raw v.description.to_s.gsub("&quot;","'").gsub(";","<br>") %></span>
			<% if v.synopsis and v.synopsis.size > 0 %>
			<% syn = v.synopsis.to_s.gsub("&quot;","'").gsub(";","<br>") %>
			<% short_syn = syn[0..60].gsub(/\s\w+$/, '...') %>
			<span class="syn">
				<%#= raw short_syn %>
				<span class="read_more">Details</span>
			</span>
			<span class="syn_hidden"><%= raw syn %></span>
			<% end %>
		</span>
	</div>
	<% end %>
</div>

app/views/videos/_index_item.html.erb
<tr <%= ("id=" + video.id.to_s) if part != 'header' %> class="<%= part %><%= " " + video.typename if part != 'header' %>">
  <% if part == "header" %>
  <th>Type</th>
  <th>Image URL</th>
  <th>Title</th>
  <th>Description</th>
  <th>Synopsis</th>
  <th>Url</th>
  <th>Edit</th>
  <th>Remove</th>
  <% elsif part == "data" %>
  <td><%= video.typename %></td>
  <td>
    <% if video.image_url and video.image_url.size > 0 %>
    <%= link_to image_tag(asset_path(video.image_url), :border => 0, :class => 'video_thumbnail index_item'), asset_path(video.image_url), :target => "_blank", :title => "" %>
    <% end %>
  </td>
  <td><%= video.title %></td>
  <td>
    <% if video.description and video.description.size > 40 %>
    <%= video.description.to_s[0..40] + "..." %>
    <% else %>
    <%= video.description.to_s %>
    <% end %>
  </td>
  <td>
    <% if video.synopsis and video.synopsis.size > 40 %>
    <%= video.synopsis.to_s[0..40] + "..." %>
    <% else %>
    <%= video.synopsis.to_s %>
    <% end %>
  </td>
  <td>
    <% if video.url and video.url.size > 0 %>
    <%= link_to image_tag(asset_path("youtube_button.png"), :class => "youtube_button"), "http://www.youtube.com/watch?v=" + video.url.split("/embed/").last, :target => "_blank", :title => "Open in YouTube" %>
    <% end %>
  </td>
  <td><%= link_to "", "javascript:void(0);", :class => "index_action edit", :title => "Edit Video Details" %></td>
  <td><%= link_to "", "javascript:void(0);", :class => "index_action delete", :title => "Hide Video from list" %></td>
</tr>
<tr class="data_edit" id="<%= video.id %>">
  <%= form_for(video, :remote => true) do |f| %>
  <td class="field">
    <%= f.label :typename %><br>
    <%= f.text_field :typename %>
  </td>
  <td class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </td>
  <td class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </td>
  <td class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </td>
  <td class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_field :synopsis %>
  </td>
  <td class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </td>
  <td class="actions">
    <%= f.submit "Save" %>
  </td>
  <% end %>
  <% end %>
</tr>

app/views/videos/_videodetails.html.erb
<div class="videodetails">
	<div id="title"></div>
	<div id="description"></div>
	<div class="vidout"></div>
</div>

app/views/videos/_videodetails_tooltip.html.erb
<div class="videodetails_tooltip">
	<div id="title"></div>
	<div id="description"></div>
	<div id="synopsis"></div>
</div>
<span class="videodetails_tooltip_arrow">&nbsp;</span>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<body>
  <table class="index_table">
    <%= render :partial => "index_item", :locals => {:part => "header"} %>

    <% @videos.each do |video| %>
    <%= render :partial => "index_item", :locals => {:part => "data", :video => video} %>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Video', new_video_path %>

  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script><%= render :file => "../assets/javascripts/videos/index", :formats => [:js] %></script>
  <link rel="stylesheet" href="/admin.css" type="text/css" media="screen" />
</body>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript"><%= render :file => "../assets/javascripts/videos/new", :formats => [:js] %></script>
<link rel="stylesheet" href="/create.css" type="text/css" media="screen" />